const disc = ['ABCDEFGHIJKLMNOPQRSTUVWXYZ ', 'EKMFLGDQVZNTOWYHXUSPAIBRCJ ', 'AJDKSIRUXBLHWTMCQGZNPYFVOE ','BDFHJLCPRTXVZNYEIWGAKMUSQO ', 'ESOVPZJAYQUIRHXLNFTGKDCMWB ', 'VZBRGITYUPSDNHLXAWMJQOFECK ']

module.exports = disc